[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_files"
version = "1.0.0"
description = "File read/write/patch commands"
requires-python = ">=3.7"
dependencies = ["diff-match-patch", "tqdm"]

